### ISSUE TITLE
FOUC on the w-input width

### ISSUE THREAD

**Issue by rainrain001** [antoniandre/nuxt-waveui#1]
I notice FOUC on the w-input component especially in the width when i wrap the w-input to w-form.

My configuration are,
i import the `wave-ui/src/wave-ui/scss/_variables` in my custom scss style. and then i call my scss custom file in the `nuxt.config.js` under the `buildModules` property and use this based in the documentation: ⤵️
```
buildModules: [
   [
      '@wave-ui/nuxt',
      {
        useScss: '~/scss/_variables.scss' // <-- my custom scss file where i import the wave-ui _variables.
      }
    ]
]
```

BUT.. if i gonna use this one below: ⤵️
```
buildModules: ['@wave-ui/nuxt']
```
it works properly.

I tried other option which is to use nuxt style resources but it seems the wave-ui _variables is not changed.

My setup is, 
- **Nuxt** `v2.15.7`
- **wave-ui** `v1.37.1`
- **PUG** `v3.0.2`
- **SASS** `v1.35.2`
- **@wave-ui/nuxt** `v1.0.3`

**Comment by antoniandre** [comment]
Hi @rainrain001,

Have you tried this only on nuxt dev (`npm run dev`)?
It could be a very tiny bit slower on dev maybe.

Since SCSS is precompiled, it should not affect the rendering speed on nuxt build and nuxt generate and you should not see any FOUC.

I am wondering if this could be due to other parts of your code triggering a change of variable too late like on mounted?

to see if it still causes the problem once the CSS is generated, run `npm run build` then `npm run start`. This will use the generated CSS. 
So if you see any FOUC, it could come from something outside of Wave UI since nothing is changing on mounted inside this Wave UI component.

Hope this help, please reopen the issue if not solved. :)
